# GET http://localhost:4000/Products
# GET http://localhost:4000/Users
# POST http://localhost:4000/Users/login
# Content-Type: application/json

# {
#     "email":"ali123@gmail.com",
#     "password":"123456"
# }

# POST http://localhost:4000/Users/register
# Content-Type: application/json

# {
#     "username":"ali",
#     "email":"ali23@gmail.com",
#     "password":"123456",
#     "role":"manager"
# }


#  PATCH http://localhost:4000/Users/66bf7af4ad695e843c805d7a
#  Content-Type: application/json
 
#  {
#     "id": 1,
#     "username": "ali",
#     "email": "ali23@gmail.com",
#     "password": "112233",
#     "role": "manager"
#  }

# GET http://localhost:4000/Products/offers

POST https://tarmeezacademy.com/api/v1/login
Content-Type: application/json

{
    "username": "ali1234@gmail.com",
    "password": "123456",
}